package CasaApp;


/**
* CasaApp/CasaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Casa.idl
* miércoles 14 de agosto de 2013 10:03:35 AM CDT
*/

public interface CasaOperations 
{
  boolean encender (String led);
} // interface CasaOperations
