package CasaApp;

/**
* CasaApp/CasaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Casa.idl
* miércoles 14 de agosto de 2013 10:03:35 AM CDT
*/

public final class CasaHolder implements org.omg.CORBA.portable.Streamable
{
  public CasaApp.Casa value = null;

  public CasaHolder ()
  {
  }

  public CasaHolder (CasaApp.Casa initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CasaApp.CasaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CasaApp.CasaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CasaApp.CasaHelper.type ();
  }

}
