package CasaApp;


/**
* CasaApp/Casa.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Casa.idl
* miércoles 14 de agosto de 2013 10:03:35 AM CDT
*/

public interface Casa extends CasaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Casa
