package PCControlApp.PCControlPackage;


/**
* PCControlApp/PCControlPackage/Pc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PCControl.idl
* lunes 10 de febrero de 2014 09:33:00 AM CST
*/

public final class Pc implements org.omg.CORBA.portable.IDLEntity
{
  public String hostname = null;
  public String sonombre = null;
  public String ip = null;
  public String ram = null;
  public String disco = null;
  public String dirmac = null;

  public Pc ()
  {
  } // ctor

  public Pc (String _hostname, String _sonombre, String _ip, String _ram, String _disco, String _dirmac)
  {
    hostname = _hostname;
    sonombre = _sonombre;
    ip = _ip;
    ram = _ram;
    disco = _disco;
    dirmac = _dirmac;
  } // ctor

} // class Pc
