package PCControlApp.PCControlPackage;


/**
* PCControlApp/PCControlPackage/PcHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PCControl.idl
* lunes 10 de febrero de 2014 09:33:00 AM CST
*/

abstract public class PcHelper
{
  private static String  _id = "IDL:PCControlApp/PCControl/Pc:1.0";

  public static void insert (org.omg.CORBA.Any a, PCControlApp.PCControlPackage.Pc that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PCControlApp.PCControlPackage.Pc extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "hostname",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "sonombre",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "ip",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "ram",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "disco",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "dirmac",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (PCControlApp.PCControlPackage.PcHelper.id (), "Pc", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PCControlApp.PCControlPackage.Pc read (org.omg.CORBA.portable.InputStream istream)
  {
    PCControlApp.PCControlPackage.Pc value = new PCControlApp.PCControlPackage.Pc ();
    value.hostname = istream.read_string ();
    value.sonombre = istream.read_string ();
    value.ip = istream.read_string ();
    value.ram = istream.read_string ();
    value.disco = istream.read_string ();
    value.dirmac = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PCControlApp.PCControlPackage.Pc value)
  {
    ostream.write_string (value.hostname);
    ostream.write_string (value.sonombre);
    ostream.write_string (value.ip);
    ostream.write_string (value.ram);
    ostream.write_string (value.disco);
    ostream.write_string (value.dirmac);
  }

}
