package PCControlApp.PCControlPackage;

/**
* PCControlApp/PCControlPackage/PcHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PCControl.idl
* martes 11 de febrero de 2014 11:34:31 AM CST
*/

public final class PcHolder implements org.omg.CORBA.portable.Streamable
{
  public PCControlApp.PCControlPackage.Pc value = null;

  public PcHolder ()
  {
  }

  public PcHolder (PCControlApp.PCControlPackage.Pc initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PCControlApp.PCControlPackage.PcHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PCControlApp.PCControlPackage.PcHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PCControlApp.PCControlPackage.PcHelper.type ();
  }

}
