package PCControlApp.PCControlPackage;


/**
* PCControlApp/PCControlPackage/PcsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PCControl.idl
* martes 11 de febrero de 2014 11:34:31 AM CST
*/

abstract public class PcsHelper
{
  private static String  _id = "IDL:PCControlApp/PCControl/Pcs:1.0";

  public static void insert (org.omg.CORBA.Any a, PCControlApp.PCControlPackage.Pc[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PCControlApp.PCControlPackage.Pc[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = PCControlApp.PCControlPackage.PcHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (PCControlApp.PCControlPackage.PcsHelper.id (), "Pcs", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PCControlApp.PCControlPackage.Pc[] read (org.omg.CORBA.portable.InputStream istream)
  {
    PCControlApp.PCControlPackage.Pc value[] = null;
    int _len0 = istream.read_long ();
    value = new PCControlApp.PCControlPackage.Pc[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = PCControlApp.PCControlPackage.PcHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PCControlApp.PCControlPackage.Pc[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      PCControlApp.PCControlPackage.PcHelper.write (ostream, value[_i0]);
  }

}
