USE [TSCI]
GO

/****** Object:  Table [dbo].[ConfigModulos]    Script Date: 09/09/2013 12:50:44 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ConfigModulos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Modulo] [varchar](50) NOT NULL,
	[Forma] [varchar](50) NOT NULL,
	[Campo] [varchar](50) NOT NULL,
	[RE] [varchar](100) NOT NULL,
 CONSTRAINT [PK_ConfigModulos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


