package PCControlApp;


/**
* PCControlApp/PCControlOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PCControl.idl
* lunes 10 de febrero de 2014 09:33:00 AM CST
*/

public interface PCControlOperations 
{
  PCControlApp.PCControlPackage.Pc[] getPcs ();
  boolean registrar (PCControlApp.PCControlPackage.Pc pc);
} // interface PCControlOperations
