package PCControlApp;


/**
* PCControlApp/PCControlOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PCControl.idl
* martes 11 de febrero de 2014 11:34:31 AM CST
*/

public interface PCControlOperations 
{
  PCControlApp.PCControlPackage.Pc[] getPcs ();
  boolean registrar (PCControlApp.PCControlPackage.Pc pc);
} // interface PCControlOperations
