package PCControlApp;


/**
* PCControlApp/PCControlHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PCControl.idl
* lunes 10 de febrero de 2014 09:33:00 AM CST
*/

abstract public class PCControlHelper
{
  private static String  _id = "IDL:PCControlApp/PCControl:1.0";

  public static void insert (org.omg.CORBA.Any a, PCControlApp.PCControl that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PCControlApp.PCControl extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PCControlApp.PCControlHelper.id (), "PCControl");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PCControlApp.PCControl read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PCControlStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PCControlApp.PCControl value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PCControlApp.PCControl narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PCControlApp.PCControl)
      return (PCControlApp.PCControl)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PCControlApp._PCControlStub stub = new PCControlApp._PCControlStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PCControlApp.PCControl unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PCControlApp.PCControl)
      return (PCControlApp.PCControl)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PCControlApp._PCControlStub stub = new PCControlApp._PCControlStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
