package PCControlApp;


/**
* PCControlApp/PCControl.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PCControl.idl
* martes 11 de febrero de 2014 11:34:31 AM CST
*/

public interface PCControl extends PCControlOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PCControl
