package PCControlApp;


/**
* PCControlApp/PCControl.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PCControl.idl
* lunes 10 de febrero de 2014 09:33:00 AM CST
*/

public interface PCControl extends PCControlOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PCControl
