//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TSCIModel", "FK_Estudiantes_Usuarios", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TestWeb.Model.Usuarios), "Estudiantes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestWeb.Model.Estudiantes), true)]

#endregion

namespace TestWeb.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TSCIEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TSCIEntities object using the connection string found in the 'TSCIEntities' section of the application configuration file.
        /// </summary>
        public TSCIEntities() : base("name=TSCIEntities", "TSCIEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TSCIEntities object.
        /// </summary>
        public TSCIEntities(string connectionString) : base(connectionString, "TSCIEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TSCIEntities object.
        /// </summary>
        public TSCIEntities(EntityConnection connection) : base(connection, "TSCIEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ConfigModulos> ConfigModulos
        {
            get
            {
                if ((_ConfigModulos == null))
                {
                    _ConfigModulos = base.CreateObjectSet<ConfigModulos>("ConfigModulos");
                }
                return _ConfigModulos;
            }
        }
        private ObjectSet<ConfigModulos> _ConfigModulos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Estudiantes> Estudiantes
        {
            get
            {
                if ((_Estudiantes == null))
                {
                    _Estudiantes = base.CreateObjectSet<Estudiantes>("Estudiantes");
                }
                return _Estudiantes;
            }
        }
        private ObjectSet<Estudiantes> _Estudiantes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuarios> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuarios>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuarios> _Usuarios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConfigModulos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConfigModulos(ConfigModulos configModulos)
        {
            base.AddObject("ConfigModulos", configModulos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Estudiantes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEstudiantes(Estudiantes estudiantes)
        {
            base.AddObject("Estudiantes", estudiantes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuarios usuarios)
        {
            base.AddObject("Usuarios", usuarios);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSCIModel", Name="ConfigModulos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConfigModulos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ConfigModulos object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="modulo">Initial value of the Modulo property.</param>
        /// <param name="forma">Initial value of the Forma property.</param>
        /// <param name="campo">Initial value of the Campo property.</param>
        /// <param name="rE">Initial value of the RE property.</param>
        public static ConfigModulos CreateConfigModulos(global::System.Int32 id, global::System.String modulo, global::System.String forma, global::System.String campo, global::System.String rE)
        {
            ConfigModulos configModulos = new ConfigModulos();
            configModulos.Id = id;
            configModulos.Modulo = modulo;
            configModulos.Forma = forma;
            configModulos.Campo = campo;
            configModulos.RE = rE;
            return configModulos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Modulo
        {
            get
            {
                return _Modulo;
            }
            set
            {
                OnModuloChanging(value);
                ReportPropertyChanging("Modulo");
                _Modulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Modulo");
                OnModuloChanged();
            }
        }
        private global::System.String _Modulo;
        partial void OnModuloChanging(global::System.String value);
        partial void OnModuloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Forma
        {
            get
            {
                return _Forma;
            }
            set
            {
                OnFormaChanging(value);
                ReportPropertyChanging("Forma");
                _Forma = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Forma");
                OnFormaChanged();
            }
        }
        private global::System.String _Forma;
        partial void OnFormaChanging(global::System.String value);
        partial void OnFormaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Campo
        {
            get
            {
                return _Campo;
            }
            set
            {
                OnCampoChanging(value);
                ReportPropertyChanging("Campo");
                _Campo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Campo");
                OnCampoChanged();
            }
        }
        private global::System.String _Campo;
        partial void OnCampoChanging(global::System.String value);
        partial void OnCampoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RE
        {
            get
            {
                return _RE;
            }
            set
            {
                OnREChanging(value);
                ReportPropertyChanging("RE");
                _RE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RE");
                OnREChanged();
            }
        }
        private global::System.String _RE;
        partial void OnREChanging(global::System.String value);
        partial void OnREChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSCIModel", Name="Estudiantes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Estudiantes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Estudiantes object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="apP">Initial value of the ApP property.</param>
        /// <param name="apM">Initial value of the ApM property.</param>
        /// <param name="matricula">Initial value of the Matricula property.</param>
        /// <param name="edad">Initial value of the Edad property.</param>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        public static Estudiantes CreateEstudiantes(global::System.Int32 id, global::System.String nombre, global::System.String apP, global::System.String apM, global::System.String matricula, global::System.Int32 edad, global::System.Int32 idUsuario)
        {
            Estudiantes estudiantes = new Estudiantes();
            estudiantes.Id = id;
            estudiantes.Nombre = nombre;
            estudiantes.ApP = apP;
            estudiantes.ApM = apM;
            estudiantes.Matricula = matricula;
            estudiantes.Edad = edad;
            estudiantes.IdUsuario = idUsuario;
            return estudiantes;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApP
        {
            get
            {
                return _ApP;
            }
            set
            {
                OnApPChanging(value);
                ReportPropertyChanging("ApP");
                _ApP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ApP");
                OnApPChanged();
            }
        }
        private global::System.String _ApP;
        partial void OnApPChanging(global::System.String value);
        partial void OnApPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApM
        {
            get
            {
                return _ApM;
            }
            set
            {
                OnApMChanging(value);
                ReportPropertyChanging("ApM");
                _ApM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ApM");
                OnApMChanged();
            }
        }
        private global::System.String _ApM;
        partial void OnApMChanging(global::System.String value);
        partial void OnApMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Matricula
        {
            get
            {
                return _Matricula;
            }
            set
            {
                OnMatriculaChanging(value);
                ReportPropertyChanging("Matricula");
                _Matricula = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Matricula");
                OnMatriculaChanged();
            }
        }
        private global::System.String _Matricula;
        partial void OnMatriculaChanging(global::System.String value);
        partial void OnMatriculaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Edad
        {
            get
            {
                return _Edad;
            }
            set
            {
                OnEdadChanging(value);
                ReportPropertyChanging("Edad");
                _Edad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Edad");
                OnEdadChanged();
            }
        }
        private global::System.Int32 _Edad;
        partial void OnEdadChanging(global::System.Int32 value);
        partial void OnEdadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                OnIdUsuarioChanging(value);
                ReportPropertyChanging("IdUsuario");
                _IdUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUsuario");
                OnIdUsuarioChanged();
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSCIModel", "FK_Estudiantes_Usuarios", "Usuarios")]
        public Usuarios Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("TSCIModel.FK_Estudiantes_Usuarios", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("TSCIModel.FK_Estudiantes_Usuarios", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuarios> UsuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("TSCIModel.FK_Estudiantes_Usuarios", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuarios>("TSCIModel.FK_Estudiantes_Usuarios", "Usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSCIModel", Name="Usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuarios object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombreUsuario">Initial value of the NombreUsuario property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static Usuarios CreateUsuarios(global::System.Int32 id, global::System.String nombreUsuario, global::System.String password)
        {
            Usuarios usuarios = new Usuarios();
            usuarios.Id = id;
            usuarios.NombreUsuario = nombreUsuario;
            usuarios.Password = password;
            return usuarios;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreUsuario
        {
            get
            {
                return _NombreUsuario;
            }
            set
            {
                OnNombreUsuarioChanging(value);
                ReportPropertyChanging("NombreUsuario");
                _NombreUsuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreUsuario");
                OnNombreUsuarioChanged();
            }
        }
        private global::System.String _NombreUsuario;
        partial void OnNombreUsuarioChanging(global::System.String value);
        partial void OnNombreUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSCIModel", "FK_Estudiantes_Usuarios", "Estudiantes")]
        public EntityCollection<Estudiantes> Estudiantes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Estudiantes>("TSCIModel.FK_Estudiantes_Usuarios", "Estudiantes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Estudiantes>("TSCIModel.FK_Estudiantes_Usuarios", "Estudiantes", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
