package HolaApp;


/**
* HolaApp/HolaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hola.idl
* lunes 12 de agosto de 2013 09:43:48 AM CDT
*/

public interface HolaOperations 
{
  String saludar ();
  int sumar (int x, int y);
  boolean encender (String led);
} // interface HolaOperations
