package HolaApp;


/**
* HolaApp/Hola.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hola.idl
* lunes 12 de agosto de 2013 09:43:48 AM CDT
*/

public interface Hola extends HolaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hola
