package HolaApp;


/**
* HolaApp/HolaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hola.idl
* lunes 10 de febrero de 2014 07:53:33 AM CST
*/

public interface HolaOperations 
{
  String saludar ();
  int sumar (int x, int y);
} // interface HolaOperations
