package CasaApp;


/**
* CasaApp/CasaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Casa.idl
* miércoles 14 de agosto de 2013 10:03:35 AM CDT
*/

abstract public class CasaHelper
{
  private static String  _id = "IDL:CasaApp/Casa:1.0";

  public static void insert (org.omg.CORBA.Any a, CasaApp.Casa that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CasaApp.Casa extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CasaApp.CasaHelper.id (), "Casa");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CasaApp.Casa read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CasaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CasaApp.Casa value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CasaApp.Casa narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CasaApp.Casa)
      return (CasaApp.Casa)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CasaApp._CasaStub stub = new CasaApp._CasaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CasaApp.Casa unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CasaApp.Casa)
      return (CasaApp.Casa)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CasaApp._CasaStub stub = new CasaApp._CasaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
