package CasaApp;


/**
* CasaApp/CasaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Casa.idl
* miércoles 14 de agosto de 2013 10:03:34 AM CDT
*/

public abstract class CasaPOA extends org.omg.PortableServer.Servant
 implements CasaApp.CasaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("encender", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CasaApp/Casa/encender
       {
         String led = in.read_string ();
         boolean $result = false;
         $result = this.encender (led);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CasaApp/Casa:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Casa _this() 
  {
    return CasaHelper.narrow(
    super._this_object());
  }

  public Casa _this(org.omg.CORBA.ORB orb) 
  {
    return CasaHelper.narrow(
    super._this_object(orb));
  }


} // class CasaPOA
