//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18051
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace TestDemoPhoneApp1.ServiceJson {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estudiante", Namespace="http://schemas.datacontract.org/2004/07/JSONService.Model")]
    public partial class Estudiante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidomaternoField;
        
        private string apellidopaternoField;
        
        private int edadField;
        
        private string idField;
        
        private string nombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidomaterno {
            get {
                return this.apellidomaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidomaternoField, value) != true)) {
                    this.apellidomaternoField = value;
                    this.RaisePropertyChanged("apellidomaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidopaterno {
            get {
                return this.apellidopaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidopaternoField, value) != true)) {
                    this.apellidopaternoField = value;
                    this.RaisePropertyChanged("apellidopaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                if ((this.edadField.Equals(value) != true)) {
                    this.edadField = value;
                    this.RaisePropertyChanged("edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceJson.IServiceJSON")]
    public interface IServiceJSON {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceJSON/DoWork", ReplyAction="http://tempuri.org/IServiceJSON/DoWorkResponse")]
        System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState);
        
        void EndDoWork(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceJSON/Saludos", ReplyAction="http://tempuri.org/IServiceJSON/SaludosResponse")]
        System.IAsyncResult BeginSaludos(System.AsyncCallback callback, object asyncState);
        
        string EndSaludos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceJSON/GetEstudiante", ReplyAction="http://tempuri.org/IServiceJSON/GetEstudianteResponse")]
        System.IAsyncResult BeginGetEstudiante(string idEstudiante, int dos, System.AsyncCallback callback, object asyncState);
        
        TestDemoPhoneApp1.ServiceJson.Estudiante EndGetEstudiante(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceJSON/GetEstudiantes", ReplyAction="http://tempuri.org/IServiceJSON/GetEstudiantesResponse")]
        System.IAsyncResult BeginGetEstudiantes(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<TestDemoPhoneApp1.ServiceJson.Estudiante> EndGetEstudiantes(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceJSONChannel : TestDemoPhoneApp1.ServiceJson.IServiceJSON, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaludosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaludosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEstudianteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetEstudianteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TestDemoPhoneApp1.ServiceJson.Estudiante Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TestDemoPhoneApp1.ServiceJson.Estudiante)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEstudiantesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetEstudiantesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<TestDemoPhoneApp1.ServiceJson.Estudiante> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<TestDemoPhoneApp1.ServiceJson.Estudiante>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceJSONClient : System.ServiceModel.ClientBase<TestDemoPhoneApp1.ServiceJson.IServiceJSON>, TestDemoPhoneApp1.ServiceJson.IServiceJSON {
        
        private BeginOperationDelegate onBeginDoWorkDelegate;
        
        private EndOperationDelegate onEndDoWorkDelegate;
        
        private System.Threading.SendOrPostCallback onDoWorkCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaludosDelegate;
        
        private EndOperationDelegate onEndSaludosDelegate;
        
        private System.Threading.SendOrPostCallback onSaludosCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetEstudianteDelegate;
        
        private EndOperationDelegate onEndGetEstudianteDelegate;
        
        private System.Threading.SendOrPostCallback onGetEstudianteCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetEstudiantesDelegate;
        
        private EndOperationDelegate onEndGetEstudiantesDelegate;
        
        private System.Threading.SendOrPostCallback onGetEstudiantesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ServiceJSONClient() {
        }
        
        public ServiceJSONClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceJSONClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceJSONClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceJSONClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DoWorkCompleted;
        
        public event System.EventHandler<SaludosCompletedEventArgs> SaludosCompleted;
        
        public event System.EventHandler<GetEstudianteCompletedEventArgs> GetEstudianteCompleted;
        
        public event System.EventHandler<GetEstudiantesCompletedEventArgs> GetEstudiantesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TestDemoPhoneApp1.ServiceJson.IServiceJSON.BeginDoWork(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoWork(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void TestDemoPhoneApp1.ServiceJson.IServiceJSON.EndDoWork(System.IAsyncResult result) {
            base.Channel.EndDoWork(result);
        }
        
        private System.IAsyncResult OnBeginDoWork(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((TestDemoPhoneApp1.ServiceJson.IServiceJSON)(this)).BeginDoWork(callback, asyncState);
        }
        
        private object[] OnEndDoWork(System.IAsyncResult result) {
            ((TestDemoPhoneApp1.ServiceJson.IServiceJSON)(this)).EndDoWork(result);
            return null;
        }
        
        private void OnDoWorkCompleted(object state) {
            if ((this.DoWorkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoWorkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoWorkAsync() {
            this.DoWorkAsync(null);
        }
        
        public void DoWorkAsync(object userState) {
            if ((this.onBeginDoWorkDelegate == null)) {
                this.onBeginDoWorkDelegate = new BeginOperationDelegate(this.OnBeginDoWork);
            }
            if ((this.onEndDoWorkDelegate == null)) {
                this.onEndDoWorkDelegate = new EndOperationDelegate(this.OnEndDoWork);
            }
            if ((this.onDoWorkCompletedDelegate == null)) {
                this.onDoWorkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoWorkCompleted);
            }
            base.InvokeAsync(this.onBeginDoWorkDelegate, null, this.onEndDoWorkDelegate, this.onDoWorkCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TestDemoPhoneApp1.ServiceJson.IServiceJSON.BeginSaludos(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaludos(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string TestDemoPhoneApp1.ServiceJson.IServiceJSON.EndSaludos(System.IAsyncResult result) {
            return base.Channel.EndSaludos(result);
        }
        
        private System.IAsyncResult OnBeginSaludos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((TestDemoPhoneApp1.ServiceJson.IServiceJSON)(this)).BeginSaludos(callback, asyncState);
        }
        
        private object[] OnEndSaludos(System.IAsyncResult result) {
            string retVal = ((TestDemoPhoneApp1.ServiceJson.IServiceJSON)(this)).EndSaludos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaludosCompleted(object state) {
            if ((this.SaludosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaludosCompleted(this, new SaludosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaludosAsync() {
            this.SaludosAsync(null);
        }
        
        public void SaludosAsync(object userState) {
            if ((this.onBeginSaludosDelegate == null)) {
                this.onBeginSaludosDelegate = new BeginOperationDelegate(this.OnBeginSaludos);
            }
            if ((this.onEndSaludosDelegate == null)) {
                this.onEndSaludosDelegate = new EndOperationDelegate(this.OnEndSaludos);
            }
            if ((this.onSaludosCompletedDelegate == null)) {
                this.onSaludosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaludosCompleted);
            }
            base.InvokeAsync(this.onBeginSaludosDelegate, null, this.onEndSaludosDelegate, this.onSaludosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TestDemoPhoneApp1.ServiceJson.IServiceJSON.BeginGetEstudiante(string idEstudiante, int dos, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetEstudiante(idEstudiante, dos, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestDemoPhoneApp1.ServiceJson.Estudiante TestDemoPhoneApp1.ServiceJson.IServiceJSON.EndGetEstudiante(System.IAsyncResult result) {
            return base.Channel.EndGetEstudiante(result);
        }
        
        private System.IAsyncResult OnBeginGetEstudiante(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string idEstudiante = ((string)(inValues[0]));
            int dos = ((int)(inValues[1]));
            return ((TestDemoPhoneApp1.ServiceJson.IServiceJSON)(this)).BeginGetEstudiante(idEstudiante, dos, callback, asyncState);
        }
        
        private object[] OnEndGetEstudiante(System.IAsyncResult result) {
            TestDemoPhoneApp1.ServiceJson.Estudiante retVal = ((TestDemoPhoneApp1.ServiceJson.IServiceJSON)(this)).EndGetEstudiante(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetEstudianteCompleted(object state) {
            if ((this.GetEstudianteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetEstudianteCompleted(this, new GetEstudianteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetEstudianteAsync(string idEstudiante, int dos) {
            this.GetEstudianteAsync(idEstudiante, dos, null);
        }
        
        public void GetEstudianteAsync(string idEstudiante, int dos, object userState) {
            if ((this.onBeginGetEstudianteDelegate == null)) {
                this.onBeginGetEstudianteDelegate = new BeginOperationDelegate(this.OnBeginGetEstudiante);
            }
            if ((this.onEndGetEstudianteDelegate == null)) {
                this.onEndGetEstudianteDelegate = new EndOperationDelegate(this.OnEndGetEstudiante);
            }
            if ((this.onGetEstudianteCompletedDelegate == null)) {
                this.onGetEstudianteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEstudianteCompleted);
            }
            base.InvokeAsync(this.onBeginGetEstudianteDelegate, new object[] {
                        idEstudiante,
                        dos}, this.onEndGetEstudianteDelegate, this.onGetEstudianteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TestDemoPhoneApp1.ServiceJson.IServiceJSON.BeginGetEstudiantes(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetEstudiantes(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<TestDemoPhoneApp1.ServiceJson.Estudiante> TestDemoPhoneApp1.ServiceJson.IServiceJSON.EndGetEstudiantes(System.IAsyncResult result) {
            return base.Channel.EndGetEstudiantes(result);
        }
        
        private System.IAsyncResult OnBeginGetEstudiantes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((TestDemoPhoneApp1.ServiceJson.IServiceJSON)(this)).BeginGetEstudiantes(callback, asyncState);
        }
        
        private object[] OnEndGetEstudiantes(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<TestDemoPhoneApp1.ServiceJson.Estudiante> retVal = ((TestDemoPhoneApp1.ServiceJson.IServiceJSON)(this)).EndGetEstudiantes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetEstudiantesCompleted(object state) {
            if ((this.GetEstudiantesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetEstudiantesCompleted(this, new GetEstudiantesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetEstudiantesAsync() {
            this.GetEstudiantesAsync(null);
        }
        
        public void GetEstudiantesAsync(object userState) {
            if ((this.onBeginGetEstudiantesDelegate == null)) {
                this.onBeginGetEstudiantesDelegate = new BeginOperationDelegate(this.OnBeginGetEstudiantes);
            }
            if ((this.onEndGetEstudiantesDelegate == null)) {
                this.onEndGetEstudiantesDelegate = new EndOperationDelegate(this.OnEndGetEstudiantes);
            }
            if ((this.onGetEstudiantesCompletedDelegate == null)) {
                this.onGetEstudiantesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEstudiantesCompleted);
            }
            base.InvokeAsync(this.onBeginGetEstudiantesDelegate, null, this.onEndGetEstudiantesDelegate, this.onGetEstudiantesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override TestDemoPhoneApp1.ServiceJson.IServiceJSON CreateChannel() {
            return new ServiceJSONClientChannel(this);
        }
        
        private class ServiceJSONClientChannel : ChannelBase<TestDemoPhoneApp1.ServiceJson.IServiceJSON>, TestDemoPhoneApp1.ServiceJson.IServiceJSON {
            
            public ServiceJSONClientChannel(System.ServiceModel.ClientBase<TestDemoPhoneApp1.ServiceJson.IServiceJSON> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DoWork", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDoWork(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DoWork", _args, result);
            }
            
            public System.IAsyncResult BeginSaludos(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Saludos", _args, callback, asyncState);
                return _result;
            }
            
            public string EndSaludos(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Saludos", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetEstudiante(string idEstudiante, int dos, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = idEstudiante;
                _args[1] = dos;
                System.IAsyncResult _result = base.BeginInvoke("GetEstudiante", _args, callback, asyncState);
                return _result;
            }
            
            public TestDemoPhoneApp1.ServiceJson.Estudiante EndGetEstudiante(System.IAsyncResult result) {
                object[] _args = new object[0];
                TestDemoPhoneApp1.ServiceJson.Estudiante _result = ((TestDemoPhoneApp1.ServiceJson.Estudiante)(base.EndInvoke("GetEstudiante", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetEstudiantes(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetEstudiantes", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<TestDemoPhoneApp1.ServiceJson.Estudiante> EndGetEstudiantes(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<TestDemoPhoneApp1.ServiceJson.Estudiante> _result = ((System.Collections.ObjectModel.ObservableCollection<TestDemoPhoneApp1.ServiceJson.Estudiante>)(base.EndInvoke("GetEstudiantes", _args, result)));
                return _result;
            }
        }
    }
}
